export const MESSAGES = {
  AUTH: {
    SIGNIN_SUCCESS: 'Signed in successfully!',
    SIGNIN_FAILED: 'Failed to sign in',
    SIGNUP_SUCCESS: 'Account created successfully!',
    SIGNUP_FAILED: 'Failed to create account',
    LOGOUT_SUCCESS: 'Logged out successfully!',
    TWO_FACTOR_REQUIRED: 'Please enter your 2FA code',
    VERIFICATION_SENT: "Check your inbox!",
    PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
    PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters',
    RESET_PASSWORD_SUCCESS: 'Password reset successfully!',
    RESET_PASSWORD_FAILED: 'Reset failed',
    INVALID_RESET_LINK: 'Invalid or expired reset link. Please request a new one.',
    CALLBACK_SUCCESS: 'Successfully authenticated',
    ERROR_OCCURRED: 'An error occurred',
  },
  RESUME: {
    UPLOAD_SUCCESS: 'Resume uploaded successfully!',
    UPLOAD_FAILED: 'Failed to upload message',
    REMOVE_SUCCESS: 'Resume removed successfully!',
    REMOVE_FAILED: 'Failed to remove resume',
    DOWNLOAD_SUCCESS: 'Resume download functionality would be implemented here',
    DOWNLOAD_FAILED: 'Failed to download resume',
    PDF_ONLY: 'Please upload a PDF file',
  },
  INTERVIEW: {
    START_SUCCESS: 'Interview started successfully!',
    START_FAILED: 'Failed to start interview',
    END_SUCCESS: 'Interview completed!',
    END_FAILED: 'Failed to end interview',
    FETCH_FAILED: 'Failed to fetch interview details',
    NO_INTERVIEW_ID: 'No interview ID provided',
    PREVIEW_SUCCESS: 'Preview created successfully!',
  },
};
